### ISSUE TITLE
🚀 Feature: Get azure devops host from config (compatibility with Azure DevOps Server)

### ISSUE THREAD

**Issue by antoniobergas** [Parfuemerie-Douglas/scaffolder-backend-module-azure-pipelines#19]
https://github.com/Parfuemerie-Douglas/scaffolder-backend-module-azure-pipelines/blob/4c9af09116d86807b0cd72cedc79942d4fd961c3/src/actions/run/createAzurePipeline.ts#L105

Hi! I'm trying to use your actions to create and run some pipelines with the Backstage scaffolder.

We use Azure DevOps Server and unfortunately this hardcoded Azure DevOps Services host make it uncompatible for us.

Can I suggest to take this value from the app-config? Or is there another way I can do so? 

Thanks for the great work 😄

**Comment by hevans-dglcom** [comment]
Hi, let me take a look at this.

**Comment by antoniobergas** [comment]
Thanks, should be something easy I guess but wanted to talk with the owner first :)

**Comment by antoniobergas** [comment]
@hevans-dglcom any news from this topic?

**Comment by hevans-dglcom** [comment]
@antoniobergas could you please take a look?

https://github.com/Parfuemerie-Douglas/scaffolder-backend-module-azure-pipelines/pull/22

I will release a new version after this is merged, I can't test it myself so I will need you to be the guinea pig :)

**Comment by hevans-dglcom** [comment]
@antoniobergas I released 0.4.4 - https://www.npmjs.com/package/@parfuemerie-douglas/scaffolder-backend-module-azure-pipelines

**Comment by hevans-dglcom** [comment]
@antoniobergas just noticed there is a package mismatch between the core scaffolder and the plugins that was breaking the build. I have pushed new versions again - see https://github.com/Parfuemerie-Douglas/scaffolder-backend-module-azure-pipelines/issues/20 for more info.

**Comment by antoniobergas** [comment]
Hi @hevans-dglcom I have an error while testing.

![image](https://github.com/Parfuemerie-Douglas/scaffolder-backend-module-azure-pipelines/assets/26031467/8ca732e0-01bf-4e06-ac7d-750377480b5a)

Could be that you missed to use the new server property in the fecth calls?

**Comment by antoniobergas** [comment]
That looks quite better! Thanks for the hard work!

**Comment by antoniobergas** [comment]
Hey @hevans-dglcom I did a short testing and worked good! tomorrow I will be debugging and doing more tests 😁
